# Generated by Django 4.2.7 on 2023-11-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0006_remove_medicalrecord_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='is_follow_up',
            field=models.BooleanField(default=False),
        ),
    ]
