# Generated by Django 4.2.7 on 2023-11-28 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hmsapp', '0008_remove_medicalrecord_is_follow_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('billID', models.AutoField(primary_key=True, serialize=False)),
                ('billdate', models.DateField()),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(max_length=50)),
                ('insurance', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsapp.patient')),
            ],
        ),
    ]
